services:
  # PHP 8.3 avec extensions Laravel
  php:
    image: php:8.3-cli
    container_name: ${PROJECT_NAME:-myapp}_php83
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "${APP_PORT:-8000}:8000"
    networks:
      - app-network
    depends_on:
      - mysql
      - redis
    environment:
      - PHP_IDE_CONFIG=serverName=Docker
    command:
      - bash
      - -c
      - |
        apt-get update && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev libzip-dev libonig-dev libxml2-dev libicu-dev git unzip curl &&
        docker-php-ext-configure gd --with-freetype --with-jpeg &&
        docker-php-ext-install -j$$(nproc) pdo pdo_mysql mysqli mbstring exif pcntl bcmath gd zip intl soap opcache &&
        pecl install redis && docker-php-ext-enable redis &&
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
        git config --global --add safe.directory /var/www/html &&
        composer install --no-interaction --optimize-autoloader &&
        php artisan key:generate --no-interaction &&
        php artisan serve --host=0.0.0.0 --port=8000

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: ${PROJECT_NAME:-myapp}_mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-laravel}
      MYSQL_USER: ${MYSQL_USER:-laravel}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # Redis
  redis:
    image: redis:alpine
    container_name: ${PROJECT_NAME:-myapp}_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - app-network

  # Mailpit
  mailpit:
    image: axllent/mailpit
    container_name: ${PROJECT_NAME:-myapp}_mailpit
    ports:
      - "${MAILPIT_SMTP_PORT:-1025}:1025"
      - "${MAILPIT_UI_PORT:-8025}:8025"
    networks:
      - app-network

  # PhpMyAdmin (optionnel)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME:-myapp}_phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER:-laravel}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-secret}
    networks:
      - app-network
    depends_on:
      - mysql

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
